### ISSUE TITLE
Support for M1/M2 Macbooks

### ISSUE THREAD

**Issue by dudo50** [open-web3-stack/parachain-launch#99]
Hi, our project that uses your library to start up the network has an issue where on M1/M2 MacBooks docker quits all containers shortly after launching. Was wondering if it is something regarding the broken library that parachain-launch uses or some library that does not support m1/m2 and if it can be resolved. It would be helpful. Currently, M platform is the way to go for future MacBooks so support is necessary. Many thanks for any kind of info.

This issue is mentioned here: https://github.com/w3f/Grant-Milestone-Delivery/pull/584#issuecomment-1278192482
And we also have it as an issue here: https://github.com/paraspell/ui/issues/7
We have also tested it on M1 MacBook and the result was the same.

With kind regards,
Dudo

**Comment by xlc** [comment]
This simply generates docker compose file. There isn't anything we can do if it failed to launch docker containers due to cpu architecture issue.

It is more likely that your docker image wasn't built properly. Try just launch them individually and see if it works.

You should also provide some logs so people can help diagnostic the issue.

I am closing as this can't really be a parachain-launch issue but feel free to post additional logs.

**Comment by dudo50** [comment]
@xlc How come it runs on Intel Macbooks and Linux-based laptops just fine? I could not find a reason why it would fail on M Macbooks.. Thanks however for your time.

With kind regards,
Dudo

**Comment by xlc** [comment]
It is impossible to tell why isn't working for you without logs.

**Comment by dudo50** [comment]
Good point, I will try to get them asap.
